### ISSUE TITLE
*** creates a 'null request' error

### ISSUE THREAD

**Issue by saltedlolly** [bulljit/Transmission-Add-Torrent-Bookmarkelet#1]
I tried this on**\* by navigatting to a specific torrent page on my iphone, clicked the bookmarklet, and then clicked the download torrent link. It then opened a new page that produced an error.

**Comment by bulljit** [comment]
I just tried it with **\* and it appears to works for me.

Several questions to help troubleshoot
1. Visit: http://www.ubuntu.com/desktop/get-ubuntu/alternative-download and ADD ubuntu-10.10-alternate-amd64.iso.torrent to make sure you have everything setup correctly.
2. Go to http://yourserver:port/transmission/web/fetchtorrent.html.  The page should render fine but of course do nothing.
3. Can you provide a screen shot of the error?  Simply press and hold the "Home" button at center bottom of the iPhone, then press and release the "Sleep" button on top right of the iPhone. This causes the iPhone to "flash" white briefly and the image is added to your "camera roll" on the phone.

This script should work under any browser...

**Comment by saltedlolly** [comment]
Okay, I have re-tried it and it seems to be working nice. I think it was a connection issue on my side. The ubuntu torrent worked fine. I think the problem I had was due to the fact that I had previously tried to download it as a 'magnet' link but it hadn't worked, and although it was removed it wouldn't let me add a new torrent. Many thanks, this is great. I have been looking for a good way to add torrents remotely.

On a side note, it was slightly unclear from the initial instructions in the readme how to download. I didn't fully understand that you first click the bookmarklet, then click the download link.

It might help others if you clarify this in the 'readme' instructions:
1. In Safari, open the page containing the Torrent file(s) you want to download
2. Once the page has loaded, click the bookmarklet, which adds an 'external window' icon next to all torrent links.
3. Click the 'download' link for the Torrent that you want
4. A new page opens, and transmits it to your remote Transmission client
5. Once completed, press the 'x' to return to the previous window. 
6. Repeat from step 3 to download other torrents from the page.

Also, one more question:

The popup 'transfer' window is not being recognised as an iphone page and appears very small. Is this normal? Currently you have to pinch-zoom to make it big enough to click the 'x' to close. It would be nice if it filled the tab.

**Comment by bulljit** [comment]
Great to that its solved!

I was so excited to get this working for myself, that I may have prematurely released it to the public.  It is far from polished.

I will add your suggestions to the readme tonight and then work on a mobile version of fetchtorrent.html this weekend.

Any further input is greatly appreciated.

**Comment by saltedlolly** [comment]
This really is excellent. I had been looking for a way to do this for ages.

You should offer this up to the Transmission team to include the relevant server files in the default Transmission install of the webui. The mobile 'clutch' ui could then have a link to save the Bookmarklet to your iPhone. It would make installation much easier. :)

**Comment by bulljit** [comment]
The compliments are motivating me :) I updated the fetchtorrent.html to render properly without zooming on the iPhone.  Do you mind testing it out?

Also, I assumed that you found this site from the Transmission Forums... If so can you leave a positive response there, so other users won't be apprehensive about trying this out?

**Comment by saltedlolly** [comment]
Fetchtorrent is now much better. Easier to close without zooming. I will add a comment on the Forums.
