### ISSUE TITLE
Transmission RPC sending Error on 'Add Torrent'

### ISSUE THREAD

**Issue by saltedlolly** [bulljit/Transmission-Add-Torrent-Bookmarkelet#10]
According to Firebug the following error is being sent:

409: Conflict

Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it. Add the updated header to your outgoing requests. When you get this 409 error message, resend your request with the updated header. This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: tddTbMty7mc2ipz4PKdEdHfUHyBCzA6cRSaMrscrhVNNZ72b

**Comment by bulljit** [comment]
Haha I've created a monster.

This is actually normal. On first request we have to get a session-id, which we then repeat to the rpc on second request. The addition of this security 409 feature is what broke older transmission bookmarklets :)
