### ISSUE TITLE
CSS Issue with Word Wrap in fetchtorrent.html (Firefox)

### ISSUE THREAD

**Issue by saltedlolly** [bulljit/Transmission-Add-Torrent-Bookmarkelet#11]
Need to fix this issue.

**Comment by saltedlolly** [comment]
I think I fixed the text wrapping issue. It took my ages of trial an error using Firebug but it worked in the end:

`body {`

`background-color: white;`

`font-family: Helvetica,sans-serif;`

`font-size: 16px;`

`margin: 0;`

`padding: 0;`

`width: 320px;`      <-- Added width.

`}`

`#diag_list {`

`background: url("images/graphics/bookmarklet/diag_mid.png") repeat-y scroll 0% 0% transparent;`

`color: #333333;`

`font-family: Arial,Helvetica,sans-serif;`

`font-size: 16px;`    <-- For some reason the font needs to be bigger

`font-weight: bold;`

`max-width: 0px;`     <--  I have no idea why this fixes it! why zero?

`padding-left: 10px;`

`padding-right: 10px;`

`text-align: center;`       <---  Centered things to make it pretty. :)

`word-wrap: break-word;`

`}`

Don't ask me why it works, but it does!

Update: Shit - There seem to still be some more issues. I think we made need to rethink the page layout. This is beyond me!

These might prove useful:

http://www.gamexe.net/css/fluid-css-speech-bubbles/

http://desandro.com/resources/css-speech-bubble-icon/

**Comment by saltedlolly** [comment]
Okay,  I just went back and retried your newer code from yesterday and it is now fine. I think it is because of my browser cache or something! Nice that I spent all that time trying to unsuccessfully fix a problem you had already solved. Doh!

**Comment by saltedlolly** [comment]
Okay, the problem is still there BUT it is intermittent. 

I have figured out that if the file name is long it wraps correctly, unless it has a '-' (hyphen) in the name. In this instance it breaks the line at the hyphen, even if it is outside the speech bubble.

I also notice that if there are spaces in the name (rather than hyphens or dots etc.) it also wraps correctly.

To clarify, a single word without spaces or a hyphen will not wrap at all. Hyphens or spaces give an opportunity for a line break.

EXAMPLES:

This.is.a.Torrent.Name.That.Will.Only.Wrap.At.the.Hyphen-
in.the.name.avi

Name with Spaces Wraps at
the correct place no problem.avi

Without.a.space.or.a.hyphen.the.name.never.wraps.avi

Maybe a solution to this to enclose the name in a fixed width table. I will try it.

**Comment by saltedlolly** [comment]
The table solution to this didn't work. The only thing I can think of is to somehow parse the returned file name, replacing the '.' in the name with spaces. Is that possible? I don't know how to do it...

**Comment by saltedlolly** [comment]
I fixed it. Upload coming. Very pleased with myself since this is my first ever javascript fix :) I am parsing the Torrent name to replace all '.' with '-'. This enables word wrapping :)

**Comment by bulljit** [comment]
Haha, I'm going to cry.

In principal, CSS will normally wrap at any [space] or [hypen] properly.  What it won't do is break a long.continous.word.without.space.or.hyphen.  In that case we need a "word-break."

I included both of the following lines, as they are methods of doing so in different browsers.  Unfortunately browsers do not implement CSS in similar ways, hence varying problems.  Just to save headache, I refuse to worry about this in IE.  But it should work in safari and firefox:

```
word-break: break-all;
word-wrap: break-word;
```

Can you make sure your page has the above line?

When testing definitively always clear your CACHE and RESTART your browser.  Also you can download an iphone emulator to test it on your computer but it looks and acts just like the iphone.

http://developer.apple.com/devcenter/mac/

Search for XCODE 3.2.3 (not version 4.0 --> which now cost $) and download it.  The iphone app will be included.  Be patient it is a VERY large file.

**Comment by bulljit** [comment]
Just saw your latest commit...

I'm not sure I like the idea of altering the name just to fix a CSS issue.  
- The given name is what the original torrent uploader meant it to be.
- What happens if the download is not the file type you specified, i.e. pdf, tar, mp3, blah blah blah, then the (.extension) is broken
- What about the name HereIsASuperLongTorrentNamingCoventionThatIsQuiteCommonWithCodersHereIsASuperLongTorrentNamingCoventionThatIsQuiteCommonWithCoders

We really need to figure out the "proper" fix rather to break the word, rather than a work-around.

Our first spat, I know.  But honestly, your changes so far have been AMAZING, thanks so much for the good work!

Also from the above mentioned msg, here is a direct link once you create an account, it is free, don't be tricked by any of Apples fees :)

https://developer.apple.com/devcenter/download.action?path=/Developer_Tools/xcode_3.2.6_and_ios_sdk_4.3__final/xcode_3.2.6_and_ios_sdk_4.3__final.dmg

**Comment by bulljit** [comment]
Haha, looks like git hub doesn't break properly either _sigh_

Dont forget to read the last 2 posts

**Comment by bulljit** [comment]
Ok so my version works in safari and the iphone.  Firefox is the problem... let me google

**Comment by saltedlolly** [comment]
Ok, understood. It is a bit of a hack I know but it does at least temporarily fix the problem for most torrents and doesn't change any wording. Exstensions I admit are a problem. I am more than willing to dump the code when we have a better fix. :)

I think it was mainly that I enjoyed seeing if I could actually figure out how to do it... ;)

Incidentally even with word-break and word-wrap added the problem is still there...

I am downloading Xcode. Thanks.

**Comment by saltedlolly** [comment]
Wow. Xcode is massive. This is going to take a while. :)

**Comment by bulljit** [comment]
Ok i fixed it!!!

DumbDumb firefox!  I'm going to pull your changes since you also edited other things and just replace my fetchtorrent.html

Stay tuned, and test it please :)  If you want to know whats good for you, you better say it works.

**Comment by bulljit** [comment]
Alright updated.

git pull

And have fun.  Seriously I want this ticket closed :)  I'm going to edit the title to be a Firefox problem not Safari

**Comment by bulljit** [comment]
P.S. good job on your first javascript :D
You're getting hooked, right?  That's why I do it.  It's like solving a puzzle.

**Comment by bulljit** [comment]
FIXED
