### ISSUE TITLE
problem with cyrillic chars in torrent name

### ISSUE THREAD

**Issue by lidow** [bulljit/Transmission-Add-Torrent-Bookmarkelet#12]
There is problem when torrent name is non-ascii (cyrillic).

It is submitted to transmission correctly, but name is url encoded, thus making it too long. So transmission is producing an error.

Some screenshots:

This is magnet link with dn in cyrillyc:
http://db.tt/ju9AUcZ

This is success submit message
http://db.tt/WNXP4Uz

This is same torrent added in transmission (name is truncated on the screenshot) + the error I receive (most likely from the FS) that the name is too long
http://db.tt/m5mvGuS

**Comment by bulljit** [comment]
Can you perform a couple tests for me?

What is the final screenshots if you...
1. add the same magnet link through the webUI itself
   and
2. if you add the link directly through the deskstop app

I just want to make sure that transmission-rpc will not url.encode the link itself, before I go adding a filter to strip nonessential characters within my code.

Thanks!!!

**Comment by lidow** [comment]
Sure,

here are some more screenshots:

# I don't have transmission desktop, so I use transmission-remote to added to

the server. 

http://db.tt/w7zRfJH

# Added through web, result is same as added through remote.

http://db.tt/w7zRfJH

# This is the result when torrent start to download

http://db.tt/c76JImw

Both methods correctly encode cyrillic chars and start to download the torrent.

---

From: bulljit 
reply@reply.github.com
To: anton.stamenov@yahoo.com
Sent: Mon, May 16, 2011 5:38:53 PM
Subject: Re: [Transmission-Add-Torrent-Bookmarkelet] problem with cyrillic chars 
in torrent name (#12)

Can you perform a couple tests for me?

What is the final screenshots if you...
1. add the same magnet link through the webUI itself
   and
2. if you add the link directly through the deskstop app

I just want to make sure that transmission-rpc will not url.encode the link 
itself, before I go adding a filter to strip nonessential characters within my 
code.

Thanks!!!

## 

Reply to this email directly or view it on GitHub:
https://github.com/bulljit/Transmission-Add-Torrent-Bookmarkelet/issues/12#comment_1173692

**Comment by bulljit** [comment]
Alright, easy fix.. can you test it with the latest fetchtorrent.html?

The problem is, I can't remember for the life of me why I decided to encodeURI prior to the rpc-json POST.  I remember finding a site that required this, but can recall the exact issue.  Oh well, guess that will be for a later headache.

Let me know how it works for you :)

BTW what country are you from?  when I searched cyrillic it came up with Russia/Ukraine.

**Comment by lidow** [comment]
Fabulous, you can close this bug :)

https://www.sugarsync.com/pf/D6747279_7399760_60560

I'm from Bulgaria, it is the mother of Cyrillic alphabet :).

http://en.wikipedia.org/wiki/Cyrillic_alphabet
