### ISSUE TITLE
Create way to install the Bookmarklet from the WebUI

### ISSUE THREAD

**Issue by saltedlolly** [bulljit/Transmission-Add-Torrent-Bookmarkelet#2]
I am thinking something along the lines of:

http://delicioussafari.com/___?javascript:window.location='dsbookmarks://save?url='+encodeURIComponent(document.location)+'&title='+encodeURIComponent(document.title)

It word be great if we could add a link next to the turtle at the bottom of the iPhone webui  called 'Get Bookmarklet' which links to a page similar to above stored in the users local Transmission install. Even better would be if the URL can already know the IP address and port of the transmission install, so the user doesn't have to manually edit the bookmarklet. Not sure if this is possible.

I have actually already written the HTML page for this as well as creating some of the images. I am no coder so I don't know how to add the link to the webui, if it's even possible. I will see if I can upload what I have so far.

**Comment by bulljit** [comment]
Installing bookmarklets on the iPhone is certainly a pain in the arse, especially for users who do NOT sync with MobileMe-Itunes.

I don't think the developers will like to add a button, for essentially a one-time use feature (the installation of the bookmark).  We could of course set up a separate webpage or blog that would use your code.

Alternatively Jordan (dev) may go for a more hidden version under the settings menu...

If the code is on the persons server, I don't think retrieving the IP:port should be an issue, but let me mull it over a bit.

**Comment by saltedlolly** [comment]
Maybe you could just add a link like this:

http://publicip:port/transmission/web/bookmarklet/___?javascript:(function(){var%20serverAddress%20=%20%22publicip:port%22;var%20a=document.getElementsByTagName(%27a%27);for(var%20i=0,j=a.length;i<j;i++){var%20linkurl%20=%20a[i].getAttribute(%27href%27);a[i].setAttribute(%27target%27,%27_blank%27);a[i].setAttribute(%27href%27,%22http://%22%20+%20serverAddress%20+%20%22/transmission/web/fetchtorrent.html?torrentlink=%22%20+%20linkurl);var%20img=document.createElement(%27img%27);img.setAttribute(%27class%27,%20%27new-window%27);img.setAttribute(%27src%27,%27data:image/gif;base64,%27+%27R0lGODlhEAAMALMLAL66tBISEjExMdTQyBoaGjs7OyUlJWZmZgAAAMzMzP///////wAAAAAAAAAAAAAA%27+%27ACH5BAEAAAsALAAAAAAQAAwAAAQ/cMlZqr2Tps13yVJBjOT4gYairqohCTDMsu4iHHgwr7UA/LqdopZS%27+%27DBBIpGG5lBQH0GgtU9xNJ9XZ1cnsNicRADs=%27);img.setAttribute(%27style%27,%27width:16px!important;height:12px!important;border:none!important;%27);a[i].appendChild(img);}})();

**Comment by saltedlolly** [comment]
On second thoughts, a good place to add this link would be on the 'open' button, where it gives you the option to upload a torrent file. The link to 'Get Bookmarklet' could appear under the form.
