### ISSUE TITLE
Private Torrents

### ISSUE THREAD

**Issue by bulljit** [bulljit/Transmission-Add-Torrent-Bookmarkelet#4]
Private torrents require authentication which is passed via a "cookie" that indicates you have previously logged in with an accepted user:pass to their website.
# Option 1: Cookie.txt File

In it's current state Transmission (TSM) will allow you to place a "cookie.txt" in your config directory.
- This is not an issue for some browsers (ie firefox) where you can export all your cookies into the "cookie.txt" format using certain extensions-addons.
- This is not so easy for Safari users, where we first have to parse the cookies.plist and then convert to "cookie.txt."  (I'm working on a simple? script for this).
# Option 2: Bookmarklet to pass the cookie

It is actually easy to retrieve the cookie via javascript and pass it along, but several issues with this...
- unless both ends are secure https:// this opens your cookies up to any would be hacker
- TSM currently does not have a function to use this information (though we could beg the developers)
- we could send the cookie to a server-side script .php (which is actually what I'm currently using in my setup) to download the torrent, but teaching the general public to set up apache on their system may be a bit too much?

I'd like to hear your thoughts...

**Comment by saltedlolly** [comment]
I'll be honest and say I don't really know since this is all a bit outside my knowledge, however:
- Unless the solution is simple then its not worth offering to end users (they can, after all, wait till they get home for private trackers! It can't be that urgent!)
- A complicated solution could be done for advanced users who really want this function which could be explained in the readme

I''ll leave this with you. :)

**Comment by saltedlolly** [comment]
You might find this useful. I just stumbled across it http://btbookmarklet.sourceforge.net/

**Comment by bulljit** [comment]
yeah that link is to utorrent, which allows cookies to be passed.  Though their system is slightly flawed because not all private sites use "uid" and "pass" cookies.

Any who, I've setup a ticket BEGGING for a similar feature to be added to transmission.  If you're curious google "CURLOPT_COOKIE" to see how this works.

**Comment by saltedlolly** [comment]
It also has an option for Transmission. Not sure sure if/how it works though.

Let me know the ticket address and I will go vote. I have plastered links back to your page on various forums. Hopefully it will generate some interest in this. I guess the hope is that if we can make it pretty and functional enough, we may get the powers that be to consider adding the server files to the Transmission binary. One can only hope! :)

**Comment by bulljit** [comment]
https://trac.transmissionbt.com/ticket/4081

**Comment by saltedlolly** [comment]
Okay I will vote. It might be worth adding a link to this from your Transmission forum post asking people to vote if they want this functionality. Probably better if it comes from you.

Also in the README file.

**Comment by ijuxda** [comment]
I implemented your proposal in trac ticket 4081, but I am unable to make comments or post patches to trac anymore (it just says "waiting for moderation" forever and several of my ip addresses appear to have been blocked completely). You can still access the code from my github fork though

https://github.com/ijuxda/transmission/tree/cookie-string  

https://github.com/ijuxda/transmission/tree/svn/cookie-string  

The svn/cookie-string branch contains the changes to the latest transmission svn/trunk, while the plain cookie-string branch is based on my master branch (which contains other changes which are useful to me but that you will probably not be interested in). So if you
have a cloned/forked transmission repository in wereHamster's fork tree and are in a branch based on his svn/trunk, you can pull with

git pull git://github.com/ijuxda/transmission.git svn/cookie-string  

to get the feature. If you have any problems, find any bugs, or have any other requests you can use my issues page or contact me via gmail.

**Comment by bulljit** [comment]
Thanks for taking notice of the ticket and the work you put into adding the feature.  I will test the new version soon for bugs.

If all goes well, do you mind if I make a request to Jordan et al, to add the changes to the "official" version?

You ofcourse will be credited =P

**Comment by ijuxda** [comment]
> If all goes well, do you mind if I make a request to Jordan et al, to add the changes to the "official" version?

I do not mind at all, you can even omit the fact that I wrote that patch since personally I do not care so much about credit as I do about just improving the program for all users.

**Comment by bulljit** [comment]
now part of svn, thanks to ijuxda and jordan :)
